### PR TITLE
fix: support running migrator in a single transaction

### PR DESCRIPTION
**Pull request by hf**
### What is being done in this PR?

`Migrator` checks if the connection it is using already has a transaction attached, in which case it does not attempt to start another transaction.

The reason why this is necessary is that developers should be given the ability to run migrations as one single all-or-nothing step, instead of as atomic sub-steps. Not all SQL dialects support this, but PostgreSQL famously does support transactional DDL.

Unfortunately the current implementation tries to start a sub-transaction, which is not well supported in many SQL dialects (for example PostgreSQL likes to use `savepoint`). This is why the migrator checks the `TX` field for an already started transaction, and does not start one on its own.

### What are the main choices made to get to this solution?

The other choice is to add proper savepoint support for the PostgreSQL dialect, but given that these are not endlessly nestable, there is little benefit.

### List the manual test cases you've covered before sending this PR:

- Tested in [GoTrue](https://github.com/supabase/gotrue) where we use this feature.

### CODE REVIEW

**Comment by hf** [comment]
@sio4 Any chance you could take a look at this?

**Comment by hf** [comment]
@markbates @stanislas-m Hey this PR has been open for a while. Is it possible to get some eyes on it?

**Comment by sio4** [comment]
Hi @,

I will check the PR soon.

**Comment by hf** [comment]
Hey @sio4, any chance I can get some eyes on this PR?

**Comment by hf** [comment]
This is not stale and very much needed!

**Pull request closed without merging**
