### PR TITLE
Add escape for special column names

### PR DESCRIPTION
**Pull request by aimicheng**
Some column names like "group" will cause syntax error when executed in MySQL.

### CODE REVIEW

**Comment by u007** [comment]
hi @aimicheng 

please ensure that you manage to run tests.sh'
it requires docker

**Comment by aimicheng** [comment]
@stanislas-m OK, I will try to make a fix for MySQL dialect. Also, I don't think it's a good idea to include support for all databases in a single package. It makes this package extremely large. How about split this package into pop, pop/mysql, pop/sqlite, ...

**Comment by mclark4386** [comment]
@aimicheng That's what the `dialect_mysql.go`, etc are. ^^

**Comment by stanislas-m** [comment]
Replaced by #383 which handles the other dialects too.

**Pull request closed without merging**
