### PR TITLE
Search all valid paths for database.yml

### PR DESCRIPTION
**Pull request by Jwonsever**
## Description

According to the [buffalo documentation](https://gobuffalo.io/en/docs/db/configuration/#database-yml) the `database.yml` file can be located in either `/config` or `/` at the project root.  The current implementation limits pop to a predefined set of lookup paths, which may or not actually include the project root based on the depth of the projects file structure.  This PR instead searches backwards for the nearest configuration, stopping once we leave GOPATH as at that point we have certainly left the project.

This was briefly mentioned in the #buffalo slack channel on July 2nd.

### Steps to Reproduce the Problem

Create a project which will use pop with the following project structure.

```
projectRoot/
projectRoot/database.yml
projectRoot/a/b/c/file.go
projectRoot/a/b/c/file_test.go
```

in file.go, attempt to call `pop.Connect(env)` in init.
run `go test ./...` from the project root.

### Expected Behavior

As the `database.yml` is at the project root, `pop.Connect` can find it automatically.

### Actual Behavior

You will get an `"unable to find pop config file"` error.  

### Workaround

You can workaround this using `pop.AddLookupPaths()`

### Info
Mac OS.
Latest Pop Development.

Needs testing on a windows environment.

### CODE REVIEW

**Comment by markbates** [comment]
Since we’re moving to modules only by the end of the year, it would makes sense to the GOMOD root as the starting point for the search, if it exists. 

Just thinking out loud. @stanislas-m make the decisions around here. :)

**Comment by Jwonsever** [comment]
Good idea.  I'll add a check for go.mod.

**Comment by Jwonsever** [comment]
Yea, I think replacing this "find the db config file" approach with a ".pop" config file would work, I think you still need the same type of search to find the ".pop" config file though.

**Comment by Pulgafree** [comment]
#529 Maybe fixs this?

**Comment by stanislas-m** [comment]
@Pulgafree No, that's a different issue.

**Comment by Pulgafree** [comment]
> @Pulgafree No, that's a different issue.

Yeah. You are Roger

**Pull request closed without merging**
