### PR TITLE
LoadFrom() now uses envy to load environment variables before establi…

### PR DESCRIPTION
**Pull request by alexsante**
I had an issue with my environment where the database connection details in my `.env` file were not being consumed by pop's config loading logic.  The simple solution was to use `envy.Load()` before the connections were made.  This allows the environment variables to replace the placeholder tokens in `database.yml`.

The only hang up I have with this solution is the dependency to the envy package.

Example database.yml:
```
development:
  dialect: "mysql"
  database: "mailedit_development"
  host: {{ env "DATABASE_HOST" }}
  port: {{ env "DATABASE_PORT" }}
  user: {{ env "DATABASE_USERNAME" }}
  password: {{ env "DATABASE_PASSWORD" }}
```

Thanks @paganotoni  for the fix suggestion

### CODE REVIEW

**Comment by markbates** [comment]
This looks good, but I would recommend not using `envy.Load()`, but instead changing the os.Getenv lines a few lines down. That will have the same affect, but it will allow for extra benefits of using envy.Get (like setting temp vars, etc...)

**Comment by alexsante** [comment]
@markbates I hesitated making that change, but I agree with your suggestion.  It makes sense.  

```
func LoadFrom(r io.Reader) error {
	tmpl := template.New("test")
	tmpl.Funcs(map[string]interface{}{
		"envOr": func(s1, s2 string) string {
			return envy.Get(s1, s2)
		},
		"env": func(s1 string) string {
			val, err := envy.MustGet(s1)
			if err != nil {
				return ""
			}
			return val
		},
	})
...
```

**Comment by alexsante** [comment]
@markbates I'll make the changes to the `Getenv` calls a few lines below, but I believe `envy.Load()` is still required.  `Get` and `MustGet` in the envy package rely on a map generated by the `Load()` func.

**Comment by markbates** [comment]
Thanks, I already made the changes so I could get the next buffalo release out. A PR was made earlier today that makes sure to load `.env` files when the `envy` package init happens, so with that update and this one, everything should be good to go. Thanks a lot

**Comment by alexsante** [comment]
Awesome

**Pull request merged**
