### PR TITLE
feat: add migrate UpTo(step)

### PR DESCRIPTION
**Pull request by zepatrik**
According to the migrate down I added a UpTo function that takes a step argument and only applies (upto) step migrations. This feature is also added to the soda cli.

### CODE REVIEW

**Comment by aeneasr** [comment]
This would be really useful for us, because we run tests against our migrations!

**Comment by zepatrik** [comment]
It might actually be use full to not only return an error but also how many steps it actually migrated up, should I add that @stanislas-m?

**Comment by stanislas-m** [comment]
Sure @zepatrik. Sorry for the delay. :)

**Comment by stanislas-m** [comment]
Thanks!

**Pull request merged**
