### PR TITLE
Add the reset command

### PR DESCRIPTION
**Pull request by stanislas-m**
It drops, recreates a database and loads a given dump.

### CODE REVIEW

**Comment by markbates** [comment]
Theres already another reset command https://github.com/gobuffalo/pop/blob/master/soda/cmd/migrate_reset.go perhaps they should be merged into one? I can see it being fairly confusing for people to understand the difference.

**Comment by stanislas-m** [comment]
Sure. I based this one on http://guides.rubyonrails.org/active_record_migrations.html#resetting-the-database, which uses the schema instead of the migrations.

I'm not sure about the one to keep, though.

**Comment by markbates** [comment]
Keep the new one, deprecate the old. He new one is better. Just make sure it falls through to migrations in case there’s no schema. I just looked at it quickly.

**Comment by u007** [comment]
also i wish to add that schema load should also auto insert all existing migration to schema_versions right?

**Comment by stanislas-m** [comment]
@u007 That's a good idea. :)

**Comment by u007** [comment]
darn, this is sad, can i rework on this later?

**Comment by stanislas-m** [comment]
@u007 Did I miss something?

**Pull request merged**
