### PR TITLE
N+1 Eager Solution

### PR DESCRIPTION
**Pull request by larrymjordan**
### Motivation
Currently, Loading Associations Strategy in pop introduce the N+1 problem for every association type (has_many, has_one, belongs_to, many_to_many).  

### Glossary 
- Association: A relationship existing in pop on a model to model level.
- Loading Association Strategy: An implementation used for loading model associations. 

### Introduce Eager Mode
By defining an Eager Mode function developers can be able to induce pop to use a different approach for loading associations. People who used to develop web applications with Rails and ActiveRecord will realize there are different “modes” or ways to load models associations: Include, Preload and Eager. Each of them have its own strategy to load data associations and different ways to query database. This flexibility also makes sense to be implemented in Pop.  

This blueprint is a proposal  I’ve been thinking of when trying to solve this need:

 ** 1. Define Eager Mode options.**
These options will allow developers to change current loading association strategy. Developers will be able to change the overall strategy, meaning they can change the default behavior for all queries made by pop, or they can just change the loading association strategy for a particular Query.

  **EagerDeafult**: current implementation, the default behavior of pop. This one introduce N+1 problem and will be used as default value for backward compatibility.

  **EagerPreload:** This mode works similar to Preload mode used in ActiveRecord.  Avoid N+1 problem by reducing the number of hits to the database but increase memory use to process and link associations to parent.

  **EagerInclude**: This mode works similar to Include mode used in ActiveRecord. It uses Left Join clauses to load associations.

**2. Activate Eager Mode.** 
Developers would use Eager Mode options in this way to change the loading association strategy.  
```go
// To change overall Eager Mode. 
   pop.SetEagerMode(pop.EagerPreload) 
// this will change the default loading associations strategy for 
// all Eager queries to be in "Preload" mode. This should be 
// used once, when setting up pop connection. 
```

```go
// To change query specific Eager Mode.
tx.SetEagerMode(pop.EagerDefault).Eager().Find(&user, id) 
// this will change the default loading associations strategy 
// for this specific query, not the one used overall.
```

This PR Introduces the implementation of two modes: `EagerDefault(Already existing)` and `EagerPreload(WIP)`   

**How to Test? **
You can check [Test Eager Preload Mode](https://github.com/larrymjordan/pop/blob/nplus1/preload_associations.go#L158)  to get an inside of how to test.  

I really appreciate any help with this to give it a little more form and cover all posible test cases.

### CODE REVIEW

**Comment by u007** [comment]
hi @larrymjordan the naming was the concern. previously i did point out that in rails, Eager means left join, while Preload means separated queries (which should not be n+1 issue, but using where condition)
if we use these names, then we shall not need to have Eager prefix

**Comment by gavbaa** [comment]
Is there any infrastructure in place for starting (Eager)Include?  This is the mode that I think is by far the most useful and flexible.  I think if this PR is going to land, it should come with both modes (and I'm willing to help, but need to know where the useful starting place is based on what you're pursuing here).

**Comment by larrymjordan** [comment]
@u007 you are correct about naming, I'm open to hear options.  Regarding default behaviour, I agree N+1 solution should be the one, and with this design we could change it easily. Also remove current implementation gradually.

@gavbaa glad to hear about it. There are three parts you can check to make your start point:

1 - this method [Query.eagerAssociations](https://github.com/gobuffalo/pop/pull/146/files#diff-80f24dcd084c70725abd0f8523ce0925R186).  has the responsibility to decide which mode implementation to use.

2- In [Loading Options] (https://github.com/gobuffalo/pop/pull/146/files#diff-3ef3327702394ae04f1ba6329e0feb52R21) you can find all posibles mode a developer can use.

3- Developers can change the mode with [Mode Changer Function](https://github.com/gobuffalo/pop/pull/146/files#diff-f49e947ec94f65964b0845af2b62845aR169)

I'm pretty bad naming functions in a first try, lol,  but that's the idea to share and discuss and came out with a solution.

**Comment by u007** [comment]
@larrymjordan maybe we can retain original Eager(), and add deprecation warning to ask user to rename to Preload, and 
introduce:
* EagerLoad() - which uses left join
* Preload() - sub sequence query via Where IN condition

this shall solve the naming issue in a progressive deprecation method

what do you think?

**Comment by larrymjordan** [comment]
@u007 totally agree. It makes more sense the intention of every method.

**Comment by gpopovic** [comment]
Any news on this one?

**Comment by JulienTant** [comment]
Hey, I'm building a heavily relation dependent system here and this could help me a lot (ATM i'm doing this by hand every time)

**Comment by gavbaa** [comment]
Julien,

Still watching this, still have a strong need for it, but I've run out of time in the short term to put direct effort in.  I'm trying to silo some time in October to take another swipe, but hoping someone else steps up and makes progress before then. :)

**Comment by garrettqmartin8** [comment]
@larrymjordan thanks for putting this together, it looks great. Curious about the status of this? What would it take to get it over the finish line?

**Comment by larrymjordan** [comment]
This is getting real Guys,  By enabling the  new `EagerMode` state to pop to be `EagerPreload` , you can reduce the number of queries that hit to the database. Here is an example showing the difference between the default eager loading and the new preload mode.

Given a many to many relationship between `Parent` and `Student`
```
student := Student{}
tx.Create(&student)

for i := 0; i < 2; i++ {
  parent := Parent{}
  tx.Create(&parent)
  tx.RawQuery("insert into parents_students(parent_id, student_id) values(?,?)", parent.ID.String(), student.ID.String()).Exec())
}
```

When we call default Eager:
``` 
parents := []Parent{}
tx.Eager().All(&parents)
``` 

A N+1 Problem is introduced. It iterates over every parent and hits the database to query every students list. 
```
 // SELECT parents.created_at, parents.id, parents.updated_at FROM parents AS parents
 
// SELECT students.created_at, students.id, students.updated_at FROM students AS students WHERE id in (select student_id from parents_students where parent_id = '1569d42e-75a3-4d05-bf16-0f65bb729532')

//SELECT students.created_at, students.id, students.updated_at FROM students AS students WHERE id in (select student_id from parents_students where parent_id = '0966a998-c1bf-4cde-bda2-7f0763b50662')
``` 

With the new `EagerPreload` mode activated, you can change the way pop loads `parents`  and its associations:

``` 
parents := []Parent{}
tx.SetEagerMode(EagerPreload).Eager().All(&parents)
``` 

```
// SELECT parents.created_at, parents.id, parents.updated_at FROM parents AS parents

// SELECT parent_id, student_id FROM parents_students WHERE parent_id in ($1, $2) | ["cc6a7c1f-f9d9-4d8f-ac69-c827f78fc1f3" "e9c42530-648a-4dda-b780-96119d81b9c1"]

// SELECT students.created_at, students.id, students.updated_at FROM students AS students WHERE id in ($1, $2) | ["82e5ddd2-3daa-4bf0-92f0-7c37b9374db1" "82e5ddd2-3daa-4bf0-92f0-7c37b9374db1"]
``` 

Only three queries hit the database in order to get all data, independently of the parents and studentys lists size .  This reduces the number of queries performed on the database and allows a more efficient use of it. 

Things I'm still working on:
* Inner associations loading.
* improve performing on many to many relation.

NOTE: you can use this for experiment purpose if you want. Let us know how this works for you.

**Comment by paganotoni** [comment]
@larrymjordan thanks for putting this one together! this is one that we are hoping a lot to get shipped into pop. If it's not too much to ask, would it be possible to have a branch in pop with this? That would allow us (and other modules users) to use it by referencing the branch.

I'm looking forward to helping with testing it and reporting any bug.

**Comment by larrymjordan** [comment]
thank you @paganotoni, that would be really helpful.

**Comment by larrymjordan** [comment]
I've created a new branch in pop repository `nplus1` for people who is interested in testing and reporting any bug. In order to use it, you can update you `go.mod` file and add this line at the end.
```
replace github.com/gobuffalo/pop => github.com/gobuffalo/pop v4.5.10-0.20190831173857-97d87b584d7a+incompatible
```

**Comment by paganotoni** [comment]
Thanks, @larrymjordan! we'll give it a shot and post any findings.

**Comment by larrymjordan** [comment]
Nested/Inner associations are now supported, update your pop module reference to be
```
replace github.com/gobuffalo/pop => github.com/gobuffalo/pop v4.11.4-0.20190905220504-0c1cb5e39943+incompatible
```

**Comment by Tecuane** [comment]
Hi team!

Where'd we end up with this? Did work move elsewhere?

**Comment by paganotoni** [comment]
@larrymjordan is there any update with regards to this?

**Comment by larrymjordan** [comment]
@paganotoni Not much of this. Following up  if anyone reports any issue about this implementation.

**Comment by larrymjordan** [comment]
@gobuffalo/pop-managers new update with fixes:
- avoid duplicity loading for nested fields that are passed as arguments twice or more.
- Avoid unwanted looping when loading associations when Preload mode is enabled globally.

use this new version:
`replace github.com/gobuffalo/pop/v5 => github.com/gobuffalo/pop/v5 v5.0.7-0.20200217141442-e8f6c77c2e5e`

**Comment by larrymjordan** [comment]
@gobuffalo/pop-managers new update with refinements:
- Add support for `order_by` tag:
`replace github.com/gobuffalo/pop/v5 => github.com/gobuffalo/pop/v5 92e6cbd51084e6eedef6c4228d8cf4f3d231e6a4`

**Comment by stanislas-m** [comment]
@larrymjordan This looks fine to me, and we gave enough time for people to test it. Can I ask you to fix the conflicts, then we can merge it? :)

**Comment by stanislas-m** [comment]
Thanks a lot @larrymjordan! 🎉

**Comment by Ilkrash** [comment]
@larrymjordan
Hi, I have found out an issue 
```
 type Risk struct {
	RiskOwner          Peopledb    `belongs_to:"risk_owner"`
	RiskOwnerID       uuid.UUID  `json:"risk_owner_id" db:"risk_owner_id"`
}
```
If  you will try to query this model with EagerPreload(), you will get nill pointer exception, but it will work with regular Eager() function
This will work 
```
 type Risk struct {
	RiskOwner          Peopledb    `belongs_to:"risk_owner" fk_id:"risk_owner_id"`
	RiskOwnerID        uuid.UUID `json:"risk_owner_id" db:"risk_owner_id"`
}
```
Regular Eager will take field name + ID by default if there was no fk_id tag provided.
Could you fix it? Or should I try to help with that?
Thank you a lot for your Eager solution, it really helped.

**Comment by larrymjordan** [comment]
Hi @Ilkrash thanks for taking notes on this. There is no any problem if you help to fix the issue. I would recommend to open an issue first with the steps to reproduce it, so we can follow it up and if you already have the solution for it, we would like to receive a PR from you.

**Pull request merged**
