### PR TITLE
[Fix] load all inner associations for every element when eager loading.

### PR DESCRIPTION
**Pull request by larrymjordan**
@markbates @stanislas-m This PR helps to solve https://github.com/gobuffalo/pop/issues/123

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Why only `All`?

**Comment by larrymjordan** [comment]
@robbyoconnor this suppose to work with every query method, guess I just put that title because of the issue attached. 🙂

**Comment by robbyoconnor** [comment]
I'll test this now :)

**Comment by larrymjordan** [comment]
@robbyoconnor guess what you propose is out of the scope of this PR. You are free to open another issue for Eager creation so we can track on it.

**Comment by robbyoconnor** [comment]
No issues!

**Comment by robbyoconnor** [comment]
Issue created #126

**Comment by stanislas-m** [comment]
@larrymjordan Is this one ready for review? :)

**Comment by robbyoconnor** [comment]
I tested this and it worked for me :)

**Comment by larrymjordan** [comment]
@stanislas-m yes it is.

**Comment by stanislas-m** [comment]
Sorry for the delay @larrymjordan. :)

**Pull request merged**
