### PR TITLE
Extract model generator

### PR DESCRIPTION
**Pull request by stanislas-m**
This is required to replace the buffalo direct call to itself, and will help to test the generator.

### CODE REVIEW

**Comment by markbates** [comment]
I would love to see this moved to buffalo-pop and eventually rewritten with genny

**Comment by markbates** [comment]
Scratch that. It should stay here, but be rewritten with genny. :)

**Comment by stanislas-m** [comment]
Will do, but in a separate PR. :)

**Comment by stanislas-m** [comment]
Ping @gobuffalo/pop-managers. I won't release the v4.7.0 without this one. :)

**Pull request merged**
