### PR TITLE
postgres: Fix inability to create model with known int primary key

### PR DESCRIPTION
**Pull request by philband**
Problem and a partial fix already described in #586

### CODE REVIEW

**Review by aeneasr — CHANGES_REQUESTED** [review]
I don't think this is correct. Primary keys should not be writeable! If this was changed, it should also be reflected in the other dialects, not just psql.

**Comment by philband** [comment]
> I don't think this is correct. Primary keys should not be writeable! If this was changed, it should also be reflected in the other dialects, not just psql.

I would argue that as a default, they should be auto-generated. However, there are situations where it is necessary to overwrite this behavior. 

Example: I need to import some basic data from a different database that already has existing references and needs matching primary keys for consistency. 

Currently, pop **silently** ignores the primary key set on the import - producing results that can not be intended and to the best of my knowledge, this behavior is not documented anywhere.

**Comment by aeneasr** [comment]
That might be true - however the submitted code does not behave as you probably expect which is why the test suites are failing. Primary keys should not be writable *after* the fact. It is true that they *could* be set before. However, for auto increments, this is a bad idea because the table's ai index is left unchanged, causing future duplicates and other potential issues. If you intend on importing int ai PKs, please do so using SQL instruction sets to avoid common problems of replicating writes instead of ex/importing full schemas.

**Comment by philband** [comment]
Okay, that explanation makes sense to me, thank you for clarifying. Closing.

**Pull request closed without merging**
