### PR TITLE
Add migration table name option

### PR DESCRIPTION
**Pull request by hadigoh**
Enables changing the default migration table name ("schema_migrations")

### CODE REVIEW

**Comment by markbates** [comment]
@hadigoh looks good, there some merge conflicts. if you could clean those up, that would be great. thanks.

**Comment by hadigoh** [comment]
Thanks @stanislas-m for resolving the conflicts :+1:

**Comment by stanislas-m** [comment]
@hadigoh Np. :)

**Comment by hadigoh** [comment]
I've added the readme to include an example to this feature :+1:

**Comment by markbates** [comment]
Thanks so much!

**Pull request merged**
