### PR TITLE
Add configuration to mute Migrator statements

### PR DESCRIPTION
**Pull request by konradreiche**
A fix for https://github.com/gobuffalo/pop/issues/10

I have introduced a new `Config` struct which I didn't want to add to the constructor so it doesn't break backwards compatibility and the config can be set manually anyway.

The question would be, should Verbose be set to true by default or did you have a different kind of flag system in mind?

### CODE REVIEW

**Comment by konradreiche** [comment]
@markbates Not sure what to do here, looks like the build failed due to external reasons.

**Comment by stanislas-m** [comment]
@konradreiche It should be fine now.

**Comment by konradreiche** [comment]
Just saw this PR https://github.com/gobuffalo/pop/pull/19 This makes mine completely unnecessary. I think we can close this one?

**Comment by stanislas-m** [comment]
@markbates Thoughts?

**Comment by konradreiche** [comment]
@stanislas-m I think he needs to play around with the logrus PR first. I am closing this one in favor of #19 for now.

**Pull request closed without merging**
