### PR TITLE
[WIP] Fizz migrations based on model arguments (like soda)

### PR DESCRIPTION
**Pull request by fluxynet**
This PR features refactoring of the code to allow soda generate fizz to generate migrations only based same logic as soda generate model

soda generate fizz currently generate empty files
whereas soda generate model can generate model structs and fizz based on command line arguments

Changes:
- FizzCmd now can generate migrations based on model data if provided
- model.addAttribute removed. code moved to attribute.newAttribute attribute.newAttribute already modifies model
- Added new modelFromArgs to create a model from arguments (to avoid repetition of code)
- Moved path flag to migrationPath variable within model.init (for consistency and readability)

### CODE REVIEW

**Comment by markbates** [comment]
Love it! Is this ready to merge? It still has WIP in the title, so I don't want to merge until you let me its finished.

**Comment by fluxynet** [comment]
I have made a second commit to remove `structTag = "json" //Of no use here, but required to be "json" or "xml" by func newModel()`
If it needs to be explained by a comment it probably is not the best way.
Simpler would be to initialize `var structTag = "json"` to the same value of the command.

Changes work as intended; but your review is paramount.

**Comment by robbyoconnor** [comment]
`git pull --rebase` and squash all these merge commits.

**Comment by markbates** [comment]
@robbyoconnor don’t worry we’ll do a squash and merge when merging it in.

**Comment by markbates** [comment]
@fluxynet it looks like there are some test errors on travis, can you look into them? thanks.

**Comment by u007** [comment]
can we have readme update for fizz?

**Comment by fluxynet** [comment]
Not sure if merge request still valid after so long.

Getting an error
`invalid operation: db.Dialect (variable of type github.com/gobuffalo/pop.dialect) has no field or method Name` on soda/cmd/generate/model.go [142]

Moving to WIP wrt to above

**Comment by robbyoconnor** [comment]
also, you should update the docs :)

**Comment by stanislas-m** [comment]
The model and migrations generators changed a lot since this PR, and @markbates is working on a rewrite in #356 using genny to make this way easier to implement.

I'm closing this PR since it needs a full rewrite based on #356 rewrite, so it'll better be a brand new PR.

**Pull request closed without merging**
